on:
  push:
    tags:
      - "*"

name: Markdown para PDF
jobs:
  build:
    name: Convertendo
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Instalando dependências
        run: |
          sudo apt-get update \
          && sudo apt-get -y install texlive-publishers \
          texlive-latex-extra \
          texlive-xetex \
          texlive-fonts-recommended \
          texlive-lang-spanish \
          texlive-lang-french \
          texlive-lang-portuguese \
          && wget -c https://github.com/jgm/pandoc/releases/download/2.9.1.1/pandoc-2.9.1.1-1-amd64.deb \
          && sudo dpkg -i pandoc-2.9.1.1-1-amd64.deb \
          && sudo gem install pandoc_abnt
      - name: Gerando PDF
        run: |
          for x in *.md; do echo >>"$x"; done \
          && pandoc -s \
          -F pandoc_abnt \
          -F pandoc-citeproc \
          --bibliography=bibliografia.bib \
          --csl \
          .github/workflows/abnt.csl \
          --template \
          .github/workflows/abnt-pandoc.latex \
          *.md \
          .github/workflows/referencias.md \
          -o ${{ github.event.repository.name }}.pdf \
          --pdf-engine=xelatex
      - name: Criando a versão
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Versão ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Subindo a versão
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ github.event.repository.name }}.pdf
          asset_name: ${{ github.event.repository.name }}.pdf
          asset_content_type: application/pdf
